spring:
  profiles:
    active: ${SPRING_PROFILE:local}

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  secret: ${JWT_SECRET}
  token:
    access-expiration-time: 1800 # 30 minutes
    refresh-expiration-time: 1209600 # 14 days
